[options]
; Rutas de módulos: los de Odoo + nuestra carpeta de addons personalizados
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo

; Contraseña maestra del gestor de bases de datos (cámbiala en producción)
admin_passwd = gamestore_admin

; Solo se sirve la base de datos "gamestore" (necesario para la API pública)
dbfilter = ^gamestore$

; Conexión a la base de datos
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

; Logs
log_level = info

